version: "3.1"
networks:
  app-tier:
    driver: bridge
services:
  mysql:
    image: ${mysql_image}
    ports:
      - '13306:3306'
    networks:
      - app-tier
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ${mysql_data_dir}:/var/lib/mysql
      - ${docker_entrypoint_initdb_d}:/docker-entrypoint-initdb.d
  phpfpm:
    image: ${phpfpm_image}
    ports:
      - '9000'
    networks:
      - app-tier
    depends_on:
      - mysql
    volumes:
      - ${doc_root_1}:/var/www/wordpress_1
      - ${doc_root_2}:/var/www/wordpress_2
      - ${doc_root_3}:/var/www/wordpress_3
  nginx:
    image: ${nginx_image}
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./.env.conf:/bitnami/nginx/conf/env.conf
      - ./wordpress.conf:/bitnami/nginx/conf/vhosts/wordpress.conf
      - ${doc_root_1}:/var/www/wordpress_1
      - ${doc_root_2}:/var/www/wordpress_2
      - ${doc_root_3}:/var/www/wordpress_3
      - ${ssl_certificate}:/bitnami/nginx/conf/cert.pem
      - ${ssl_certificate_key}:/bitnami/nginx/conf/cert.key
